# NumPy – Avançado

- importando biblioteca

In [2]:
import numpy as np

- Criando array numpy

In [7]:
#Exibir apenas valores pares
arr = np.array([1,2,3,4,5,6,7,8,9,10])

- Funções where

In [6]:
print(arr[np.where(arr%2==0)])

[ 2  4  6  8 10]


- Substituindo elemenos com where

In [9]:
arr2 = np.where(arr%2==0, 0,arr)

In [10]:
print(arr2)

[1 0 3 0 5 0 7 0 9 0]


- Substituindo  elementos - Comando put

In [12]:
np.put(arr2,1,10)

In [13]:
print(arr2)

[ 1 10  3  0  5  0  7  0  9  0]


## Valores NaN

In [14]:
arr = np.array([1,2,4,5,np.nan,0,2,3,np.nan,np.nan,0,3,4,6])

In [15]:
#Existe elementos NaN no array?
print(np.isnan(arr))

[False False False False  True False False False  True  True False False
 False False]


In [16]:
# Onde ele e nulo? vai exibir os indices
np.where(np.isnan(arr))

(array([4, 8, 9], dtype=int64),)

In [17]:
#Onde for NaN quero que substitua por 10
arr = np.where(np.isnan(arr),10,arr)

In [18]:
print(arr)

[ 1.  2.  4.  5. 10.  0.  2.  3. 10. 10.  0.  3.  4.  6.]


## Reshape

- Faz a transformação de array em matriz

In [21]:
arr = np.array([1,2,3,4,5,6])

In [24]:
#Transformando array em matriz (duas linhas, três colunas)
arr2 = arr.reshape(2,3)

In [23]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [25]:
arr3 = arr.reshape(3,2)

In [26]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


## Comando stack

- stack junta todos os elementos convertendo uma matriz e apenas uma linha

In [29]:
np.hstack(arr2)

array([1, 2, 3, 4, 5, 6])