# Numpy - intermediário

### Diferentes operações matemática utilizando a biblioteca Numpy do Python

In [1]:
import numpy as np

### Vetor espaçado lineamente

- (valor minimo, valor máximo, quantos pontos)

In [2]:
X = np.linspace(0,1,11)
print(X)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


- retstep define um passo fixo 0.1

In [3]:
X = np.linspace(0,1,11,retstep=True)
print(X)

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]), 0.1)


In [6]:
X = np.linspace(0,1,11,endpoint=False)
print(X)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


### Valor Absoluto

In [9]:
X = np.array([-3,-2,-1,0,1,2,3])

- Calculo do modulo

In [10]:
Y = np.abs(X)
print(Y)

[3 2 1 0 1 2 3]


### Posição de maior valor

In [18]:
X = [1,4,7,1,0,2]

In [20]:
np.argmax(X)

2

In [21]:
X[np.argmax(X)]

7

### Posição Menor valor

In [24]:
np.argmin(X)

4

In [25]:
X[np.argmin(X)]

0

- Potencias

In [26]:
X = np.array([1,2,3,4,5])

In [27]:
Y = np.power(X,2)

In [28]:
print(Y)

[ 1  4  9 16 25]


In [33]:
power_z = np.array([1,2,3,4,5])

- fazendo potencia dos elementos da lista um a um 

In [34]:
Z = np.power(X,power_z)

In [35]:
print(Z)

[   1    4   27  256 3125]


- Arredondamentos

In [37]:
X = [1.2,1.46,1.51,1.69,1.82,1.999]

- Valor mais próximo

In [39]:
Y = np.around(X)

In [40]:
print(Y)

[1. 1. 2. 2. 2. 2.]


- Considerando uma casa decimal

In [42]:
Z = np.around(X, decimals=1)

In [43]:
print(Z)

[1.2 1.5 1.5 1.7 1.8 2. ]


- Valor inteiro mais próximo

In [45]:
W = np.rint(X)

In [46]:
print(W)

[1. 1. 2. 2. 2. 2.]


- Valor inteiro mais próximo de zero

In [47]:
X = [-2.6,-1.2,0.6,0.2,0.9,1.5,2.9]

In [48]:
A = np.fix(X)

In [49]:
print(A)

[-2. -1.  0.  0.  0.  1.  2.]


### Floor

- Floor do escalar ***x*** é maior inteiro ***i*** de modo que ***i<=x***

In [52]:
B = np.floor(X)

In [53]:
print(B)

[-3. -2.  0.  0.  0.  1.  2.]


### Ceil

- Ceil do escalar ***x*** é menor inteiro ***i*** de modo que ***i>=x***

In [57]:
C = np.ceil(X)

In [58]:
print(C)

[-2. -1.  1.  1.  1.  2.  3.]


### Valor truncado

In [60]:
D = np.trunc(X)

In [61]:
print(D)

[-2. -1.  0.  0.  0.  1.  2.]


- Produto

In [63]:
X = [2,5]

In [64]:
#produto = 2*5
print(np.prod(X))

10


In [65]:
X = [[2,4],[3,5]]

In [67]:
#Produto = 2*4*3*5
print(np.prod(X))

120


In [68]:
#Produto = 2*4 e 3*5
print(np.prod(X,axis=1))

[ 8 15]


In [69]:
#Produto = 2*3 e 4*5
print(np.prod(X,axis=0))

[ 6 20]


In [70]:
#Produto = 2*3*2
print(np.prod([3,2], initial=2))

12


### Soma

In [72]:
X = [1,2,3,4,5,6]

In [73]:
soma1 = np.sum(X)

In [74]:
# soma = 1+2+3+4+5+6
print(soma1)

21


In [75]:
X = [[1,2,3],[3,6,3]]

In [76]:
soma2 = np.sum(X,axis=0)

In [77]:
# soma = 1+2, 2+6, 3+3
print(soma2)

[4 8 6]


In [78]:
soma3 = np.sum(X,axis=1)

In [79]:
#soma = 1+2+3, 3+6+3
print(soma3)

[ 6 12]
