## - Criação e manipulação de arranjos multidimensonais utilizando a biblioteca Numpy do Python

<center><img src="https://raw.githubusercontent.com/paulocesarcsdev/Data_Science_Tools/master/Numpy/img/icone2.png"><center/>

### Criação e manipulação de arranjos multidimensionais utilizando Numpy do Python

- Importando a biblioteca Numpy

In [1]:
import numpy as np

### Criando um array Numpy

In [2]:
temporario_1 = [1, 2, 3, 4, 5]
temporario_2 = [1.2, 2.3, 3.4, 4.5, 5.6]

- Convertendo lista para array numpy

In [3]:
a_conversao = np.array(temporario_1)
b_conversao = np.array(temporario_2)

- Imprimindo as lista

In [4]:
print(temporario_1)
print(temporario_2)

[1, 2, 3, 4, 5]
[1.2, 2.3, 3.4, 4.5, 5.6]


In [5]:
print(a_conversao)
print(b_conversao)

[1 2 3 4 5]
[1.2 2.3 3.4 4.5 5.6]


### Exibindo o tipo do array 

In [6]:
a_conversao.dtype

dtype('int32')

In [7]:
b_conversao.dtype

dtype('float64')

### Criando array manulamente com dtype float64

In [9]:
c_vetor = np.array([[1,2,3],[3,4,5]], dtype='float64')

In [10]:
c_vetor

array([[1., 2., 3.],
       [3., 4., 5.]])

In [11]:
c_vetor.dtype

dtype('float64')

### Exibindo formato do array

In [13]:
c_vetor.shape

(2, 3)

### Determinando a dimesão do array

In [15]:
c_vetor.ndim

2

### Determinando o número de elementos do array

In [17]:
c_vetor.size

6

### Determinando o tipo da váriavel 

In [19]:
type(c_vetor)

numpy.ndarray

### Criando uma matriz 3x4 com todos elementos nulos e do tipo inteiro

In [21]:
np.zeros((3,4), dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

### Criando uma matriz 4x5 com todos elementos iguais a um e do tipo float

In [23]:
np.ones((4,5), dtype='float64')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
### Criando uma matriz 3x3 com todos os elementos iguais a 5

In [25]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### Criando uma matriz 3x3 identidade

In [27]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Operações com matriz

### Somando elementos do array com número constante

In [32]:
np.array([1,2,3]) + 2

array([3, 4, 5])

### Somando dois arrays de tamanhos iguais

In [34]:
np.array([1,2,3]) + np.array([1,2,3])

array([2, 4, 6])

In [35]:
a = np.array([1,2,3])
b = np.array([1,2])
c = np.array([3,4,5])

In [39]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

O  número (dimensões)de linha precisa ser igual ao número de coluna nas operações com matriz

### O que fazer para efeitar essa tipo de erro?

In [40]:
if(a.shape == b.shape):
    print(a+b)
else:
    print('Impossível somar')

Impossível somar


In [41]:
if(a.shape == c.shape):
    print(a + c)
else:
    print('Impssível somar')

[4 6 8]


### Somando array 2D

In [43]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,5,8],[2,1,8]])

In [44]:
a+b

array([[ 4,  7, 11],
       [ 6,  6, 14]])

In [45]:
a-b

array([[-2, -3, -5],
       [ 2,  4, -2]])

In [46]:
a*b

array([[ 3, 10, 24],
       [ 8,  5, 48]])

## Manipulando elementos na matriz

### Adicionando elementos no array

In [49]:
tmp = [1,2,3,4]

In [50]:
tmp.append(5)

In [51]:
tmp

[1, 2, 3, 4, 5]

### Removendo elemento do array

In [53]:
np.delete(tmp,4)

array([1, 2, 3, 4])

## Produto escalar de dois arranjos

In [55]:
a = [1,2,3]
b = [4,5,6]
c = np.dot(a,b)

In [56]:
c

32

## Somando elementos do array

In [58]:
a = np.array([[1,2,3],[4,5,6]])

In [59]:
print(np.sum(a))

21


In [68]:
# axis= 0 soma coluna
print(np.sum(a,axis=0))

[5 7 9]


In [67]:
# axis= 1 soma linha
print(np.sum(a,axis=1))

[ 6 15]


## Transposta de uma matriz

In [63]:
a = np.array([[1,2,3],[4,5,6]])

In [64]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Utilizando condicionais

In [81]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [82]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [83]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
a[(a>5) & (a<9)]

array([6, 7, 8])

In [85]:
a[(a<2)| (a>10)]

array([ 1, 11, 12, 13, 14, 15])

## Exibindo indices especifícos

In [86]:
a = [1,2,3,4,5,6]

In [87]:
a[2]

3

In [96]:
#Exibir o ultimo elemento
a[-1]

6

In [97]:
#Exibir os dois primeiros elementos
a[0:2]

[1, 2]

In [98]:
#Comece do terceiro elemento
a[-3:]

[4, 5, 6]

In [91]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [99]:
#Exibir a primeira linha da matriz
b[0]

array([1, 2, 3, 4])

In [93]:
b[:,1]

array([2, 6])

In [100]:
#Primeira linha e todos os elementos
b[1,:]

array([5, 6, 7, 8])

## Invertendo valores

In [101]:
b[::-1]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [102]:
a[::-1]

[6, 5, 4, 3, 2, 1]