# NumPy – Avançado

- importando biblioteca

In [2]:
import numpy as np

- Criando array numpy

In [7]:
#Exibir apenas valores pares
arr = np.array([1,2,3,4,5,6,7,8,9,10])

- Funções where

In [6]:
print(arr[np.where(arr%2==0)])

[ 2  4  6  8 10]


- Substituindo elemenos com where

In [9]:
arr2 = np.where(arr%2==0, 0,arr)

In [10]:
print(arr2)

[1 0 3 0 5 0 7 0 9 0]


- Substituindo  elementos - Comando put

In [12]:
np.put(arr2,1,10)

In [13]:
print(arr2)

[ 1 10  3  0  5  0  7  0  9  0]


## Valores NaN

In [14]:
arr = np.array([1,2,4,5,np.nan,0,2,3,np.nan,np.nan,0,3,4,6])

In [15]:
#Existe elementos NaN no array?
print(np.isnan(arr))

[False False False False  True False False False  True  True False False
 False False]


In [16]:
# Onde ele e nulo? vai exibir os indices
np.where(np.isnan(arr))

(array([4, 8, 9], dtype=int64),)

In [17]:
#Onde for NaN quero que substitua por 10
arr = np.where(np.isnan(arr),10,arr)

In [18]:
print(arr)

[ 1.  2.  4.  5. 10.  0.  2.  3. 10. 10.  0.  3.  4.  6.]


## Reshape

- Faz a transformação de array em matriz

In [21]:
arr = np.array([1,2,3,4,5,6])

In [24]:
#Transformando array em matriz (duas linhas, três colunas)
arr2 = arr.reshape(2,3)

In [23]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [25]:
arr3 = arr.reshape(3,2)

In [26]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


## Comando stack

- stack junta todos os elementos convertendo uma matriz e apenas uma linha

In [29]:
np.hstack(arr2)

array([1, 2, 3, 4, 5, 6])

### Valores em comum

In [32]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([1,12,3,45,23,67,4])

In [33]:
comum = np.intersect1d(a,b)

In [34]:
print(comum)

[1 3 4]


### Removendo valores comum

In [37]:
np.setdiff1d(a,b)

array([ 2,  5,  6,  7,  8,  9, 10])

### Verificando se elementos estão no array

In [39]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [40]:
print(np.isin(a,[1,5,8]))

[ True False False False  True False False  True False False]


### Invertendo arranjo

In [42]:
print(np.flip(a))

[10  9  8  7  6  5  4  3  2  1]


### Ordenando elementos

In [44]:
arr = np.array([10,45,32,67,2,0,20,45,78])

In [45]:
arr = np.sort(arr)

In [46]:
print(arr)

[ 0  2 10 20 32 45 45 67 78]


In [47]:
arr2 = np.array([[2,6,1],[8,2,0],[0,3,1]])

In [48]:
print(arr2)

[[2 6 1]
 [8 2 0]
 [0 3 1]]


In [49]:
arr2_0 = np.sort(arr2)

In [50]:
print(arr2_0)

[[1 2 6]
 [0 2 8]
 [0 1 3]]


### Ordenando na linha

In [55]:
arr2_1 = np.sort(arr2,axis=1)


In [56]:
print(arr2_1)

[[1 2 6]
 [0 2 8]
 [0 1 3]]


### Ordenando na coluna

In [58]:
arr2_1 = np.sort(arr2,axis=0)

In [59]:
print(arr2_1)

[[0 2 0]
 [2 3 1]
 [8 6 1]]


### Repetir sequência

In [61]:
arr = np.array([1,2,3])

In [63]:
arr2 = np.tile(arr,2)

In [64]:
print(arr2)

[1 2 3 1 2 3]


### Valores únicos

In [66]:
arr = np.array([1,2,3,4,1,4,0,2,3,1,0,5,10])

In [67]:
print(np.unique(arr))

[ 0  1  2  3  4  5 10]


### Valores únicos com contagem

In [69]:
valores, contagem = np.unique(arr,return_counts=True)

In [70]:
print(valores)

[ 0  1  2  3  4  5 10]


In [71]:
print(contagem)

[2 3 2 2 2 1 1]
